// import sx from "../images/sx.jpg";

export const data = [
    {
        id:1,
        house:"Sherlock House",
        price:"$2200",
        type:"House",
        addr:"231 block near dighi street , Raxaul",
    },
    {
        id:2,
        house:"Watson House",
        price:"$1500",
        type:"Company",
        addr:"231 block near dighi street , Motihari",
    },
    {
        id:3,
        house:"Western Avenue",
        price:"$3000",
        type:"Office",
        addr:"231 block near dighi street , Meerut",
    },
    {
        id:4,
        house:"Amaan Hilton",
        price:"$2500",
        type:"House",
        addr:"231 block near dighi street , Hyderabad",
    },
    {
        id:5,
        house:"Hilton Carter",
        price:"$800",
        type:"Company",
        addr:"231 block near dighi street , Uttrakhand",
    },
    {
        id:6,
        house:"Yorkingel",
        price:"$11520",
        type:"office",
        addr:"231 block near dighi street , Jammu",
    },
    {
        id:7,
        house:"White House",
        price:"$8400",
        type:"House",
        addr:"231 block near dighi street , UP",
    },
    {
        id:8,
        house:"Palm Harbor",
        price:"$4000",
        type:"Company",
        addr:"231 block near dighi street , Kolkata",
    },
    {
        id:9,
        house:"Beverly SpringField",
        price:"$990",
        type:"Office",
        addr:"231 block near dighi street , Pune",
    },
    {
        id:10,
        house:"Faulkner Ave",
        price:"$2312",
        type:"House",
        addr:"231 block near dighi street , Mumbai",
    },
    {
        id:11,
        house:"Elementary Residency",
        price:"$5000",
        type:"Company",
        addr:"231 block near dighi street , delhi",
    },
    {
        id:12,
        house:"Akuma house",
        price:"$1213",
        type:"Office",
        addr:"231 block near dighi street , Agra",
    },
    {
        id:13,
        house:"Freemangood",
        price:"$4500",
        type:"Company",
        addr:"231 block near dighi street , Chennai",
    },
    {
        id:14,
        house:"Easy home",
        price:"$2000",
        type:"House",
        addr:"231 block near dighi street , Banglore",
    },
]
